# Generated by Django 4.2 on 2023-04-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('data_region_id', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('T', 'Timed'), ('M', 'Manual'), ('O', 'Other')], max_length=1)),
                ('timestamp', models.DateTimeField(verbose_name='state capture time')),
                ('result', models.CharField(max_length=10, verbose_name='fetch result')),
                ('logfile', models.BooleanField(verbose_name='has error log')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ffxivws.datacenter')),
            ],
        ),
        migrations.CreateModel(
            name='WorldState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONL', 'Online'), ('MTP', 'Partial Maintenance'), ('MTF', 'Maintenance')], max_length=3)),
                ('classification', models.CharField(choices=[('ST', 'Standard'), ('NW', 'New'), ('PF', 'Preferred'), ('CG', 'Congested')], max_length=2)),
                ('char_creation', models.SmallIntegerField(choices=[(1, 'Character creation available'), (0, 'Character creation unavailable')])),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffxivws.snapshot')),
                ('world', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ffxivws.world')),
            ],
        ),
        migrations.AddField(
            model_name='datacenter',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ffxivws.region'),
        ),
    ]
