services:
  web:
    build:
      context: .
      target: fws_web
    restart: "no"
    environment:
      FWSWEB_ENVIRONMENT: production
      FWSWEB_DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: fws
      POSTGRES_PASSWORD: fws_pass
      POSTGRES_DB: fws
      PGDATA: /var/lib/postgresql/data  # explicitly set it to the default location, because why not?
    volumes:
      - type: bind
        source: ./production_data/db
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
        read_only: false
    command: ["postgres",
              "-c", "client_encoding=UTF8",
              "-c", "default_transaction_isolation=read committed",
              "-c", "timezone=UTC"]

  rabbitmq:
    image: rabbitmq:3.12-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: fws
      RABBITMQ_DEFAULT_PASS: fws_pass
      RABBITMQ_DEFAULT_VHOST: fws_vhost

  rev_proxy:
    build:
      context: .
      target: nginx_rev
    restart: "no"
    depends_on:
      - web
    ports:
      - "8088:80"

  celery_worker:
    build:
      context: .
      target: fws_cel
    restart: "no"
    command: ["worker", "--loglevel=DEBUG", "--logfile=/tmp/celery.log"]
    environment:
      FWSWEB_ENVIRONMENT: production
      FWSWEB_DB_HOST: db
    depends_on:
      - rabbitmq
      - db

  celery_beat:
    build:
      context: .
      target: fws_cel
    restart: "no"
    command: ["beat", "--loglevel=DEBUG", "--logfile=/tmp/celery.beat.log",
              "--scheduler=django_celery_beat.schedulers:DatabaseScheduler"]
    environment:
      FWSWEB_ENVIRONMENT: production
      FWSWEB_DB_HOST: db
    depends_on:
      - celery_worker
      - db
